// try catch

try {
    console.log("try this");
    wrongVar += 1;
} catch (error) {
    console.log("woopsie, didn't work !");
}